version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: packhcontroll
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123uyt123980
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: app-proj/packhousecontroll
    #image: ghcr.io/cflb-working/evelinproj:$IMAGE_TAG
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      USE_POSTGRES: true
      DATABASE_NAME: packhcontroll
      DATABASE_USER: root
      DATABASE_PASSWORD: 123uyt123980
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app
   
volumes:
  postgres_data:
