name: Django CI -  Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-app:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Wait for database to be ready
      run: |
        for i in {1..30}; do
          if pg_isready -h 0.0.0.0 -U myuser; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Check PostgreSQL logs
      run: docker logs $(docker ps -q --filter "ancestor=postgres:latest")

    - name: Test Hostname Resolution (Debug) # Added debugging step
      run: ping -c 3 0.0.0.0

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.2'

    - name: Install dependencies
      run: |
        cd $(pwd)/app-proj/packhousecontroll
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        cd $(pwd)/app-proj/packhousecontroll
        python manage.py migrate

    - name: Run tests
      run: |
        cd $(pwd)/app-proj/packhousecontroll
        python manage.py test